### PR TITLE
Feature/teaser page #1

### PR DESCRIPTION
**Pull request by yeti-detective**
Reference Issue #1 

I copied the Project Overview from the existing [BSA dual power map page](https://blacksocialists.us/dual-power-map)

UX is not my strong suit. This is a first draft. Let me know if anything should be changed.

### CODE REVIEW

**Comment by mooooooooooooooon** [comment]
@yeti-detective heya. i think we should hold off on merging this since master will be our production branch, but let's leave this open for now and once there's a `teaser` branch & zeit ci going we can update the target of the PR & merge it in. can probably make that happen tomorrow. cool?

**Comment by 2ndline** [comment]
We could make a dev/qa branch and change the target branch of the PR to
that branch

**Comment by yeti-detective** [comment]
Fully agree @mooooooooooooooon and @2ndline 

The first thing I thought when I woke up this morning was, "that shouldn't be a merge to master..."

**Comment by mooooooooooooooon** [comment]
@2ndline that's what the `teaser` branch is

**Pull request merged**
